### ISSUE TITLE
Version for VS 2017

### ISSUE THREAD

**Issue by dfarrNTST** [emonney/QuickApp#1]
Can you create a version for use within VS 2017 with the latest NETStandard/ASP.Net Core releases?

**Comment by emonney** [comment]
Sure, this is upcoming

**Comment by renatotkr** [comment]
@emonney amazing template, do you have any updates about vs2017? Thanks

**Comment by emonney** [comment]
The VS2017 extension is available in the link below. The github project will be updated this weekend
https://marketplace.visualstudio.com/items?itemName=adentum.QuickApp-ASPNETCoreAngularXProjectTemplate
