### ISSUE TITLE
Updates for QuicApp Pro

### ISSUE THREAD

**Issue by ukozdan** [emonney/QuickApp#102]
Hi,
     How do I get updates for QuickApp Pro? I see activity on QuickApp, can I just overwrite files in QuicApp Pro with the files in this repository?

**Comment by tonydrake** [comment]
good question - I see a relase to core 2.1 - but I've got the pro templates as a base for my application.

**Comment by emonney** [comment]
No. They're not the same projects.
Where as the concepts are the same the underlying technologies sometimes differ.
The recommended approach to update an existing project is to do a diff between your current version and an update of the same edition of QuickApp. Take the differences and apply the changes to your own solution.
In most cases updates for the various editions are available within a week of each other.
