### ISSUE TITLE
what is the difference between your project and asp.net zero?

### ISSUE THREAD

**Issue by raasforce** [emonney/QuickApp#103]
your price seems very cheap. I think you are missing Multi-tenant and code generator. I would like to review your application framework, how do I do that?

**Comment by emonney** [comment]
The focus of QuickApp is to keep things simple and straight forward without deviating so much from the guidelines the various technologies (asp.net core and angular) propose.
This makes it efficient and faster for developers to adopt and be productive with.

You can see demos for the various editions here:
OpenSource: http://quickapp.ebenmonney.com
Standard Edition: http://quickapp-standard.ebenmonney.com
Pro Edition: http://quickapp-pro.ebenmonney.com
