### ISSUE TITLE
App template is not compatible with IE 11

### ISSUE THREAD

**Issue by sparra1000** [emonney/QuickApp#104]
With a clean install of the template Angular 5 ASP.Net Core 2.0, it hangs on the loading page in IE 11.0.9600. Error looks like it's in the polyfills.bundle.js file in the browser debugger :
"throw TypeError(t+" is not iterable!")"

Same exact issue using the live demo link:
http://quickapp.ebenmonney.com/

Works fine in Firefox from Visual Studio and the demo link.

**Comment by trailblazer2006** [comment]
+1
Chrome, Edge - ok
IE 11.371.16299.0 - fail

**Comment by IngoManthey** [comment]
Hi,
see https://github.com/angular/material2/issues/7374

**Comment by sparra1000** [comment]
Dropping angular support for IE11 already?  1/2020 is almost 2 years from now.

**Comment by sparra1000** [comment]
I uncommented these in the polyfill.ts and it works.

 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';

Found this here: [https://stackoverflow.com/a/42426495](https://stackoverflow.com/a/42426495)

**Comment by renathy** [comment]
Why this issue is closed? It still happens when new template is used.

**Comment by emonney** [comment]
IE 11 is not supported by default. But to support it read through the polyfills.ts file and uncomment the necessary IE 11 requirements.
See @sparra1000  answer above if you need extra guidance
