### ISSUE TITLE
ng2-toasty missing depedency error

### ISSUE THREAD

**Issue by seekaprice** [emonney/QuickApp#105]
i'm getting this error after i run command -> npm install
and then command -> npm ls --depth=0
npm ERR! peer dep missing: @angular/core@^2.4.7 || ^4.0.0, required by ng2-toasty@4.0.3
it doesn't seem ng2-toasty is compatible with angular 5, or am i missing something?

**Comment by Mynken** [comment]
@seekaprice  ng2-toasty@4.0.3 - is for Angular 4, and you are running Angular 5+ app

**Comment by emonney** [comment]
ng2-toasty was dropped during the angular 5 transitioning. The project now uses ngx-toasta which works through angular 5 to angular 7 at the time of writing this reply.
Grab the latest bits of QuickApp to for the fix
