### ISSUE TITLE
Impossible to log out and log in again

### ISSUE THREAD

**Issue by IngoManthey** [emonney/QuickApp#106]
Hi,

I make a login as admin. All works fine. Then I make logout and the login control are open. I want to make a login again.

I test it with equal and other  credentials. I debug a little bit.
At first he call the ProfileService.GetProfileDataAsync. The I see the welcome  message. Then I see in Error Message and in the console I can read:

everity: "error", Summary: "Loading error", detail: "No data could be retrieved from the server.
Error: session expired ", Error:" "session expired" "

after that the login component open again. The problem only occurs when the option remember me is clicked.

 Ingo

**Comment by emonney** [comment]
This is an old post. Is this still an issue? 
If you still run into this paste the relevant contents from your logs folder here and reopen this issue
