### ISSUE TITLE
Swagger does not work with any authorized route

### ISSUE THREAD

**Issue by n00dl3s** [emonney/QuickApp#110]
When using Swagger to test routes, any authorized route will return a 401.

**Comment by n00dl3s** [comment]
Was able to resolve this by adding.

` c.AddSecurityDefinition("Bearer", new ApiKeyScheme
                {
                    In = "header",
                    Description = "Please insert JWT with Bearer into field",
                    Name = "Authorization",
                    Type = "apiKey"
                });
                c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
                {
                    { "Bearer", new string[] { } }
                });`

And getting the Bearer key in the debug console, after logging in through the password flow in swagger. 

Is there a better way to do this?

**Comment by thomas1008** [comment]
plz howa u test swagger api
