### ISSUE TITLE
No Package.json file

### ISSUE THREAD

**Issue by maylortaylor** [emonney/QuickApp#116]
I have not been able to get this application working and I believe it has to do with the fact that there is no package.json file in the QuickApp folder.

Whenever I run the app all i get is a 500 server error and my webpage says "Cannot GET /"

**Comment by rafsanulhasan** [comment]
IMO, This is a webpack build issue. The package.json file is located under **ClientApp** folder. Run `npm install` on that folder and then run the project. It should work.

**Comment by emonney** [comment]
If you don't have package.json in your configuration you might have a corrupted package. Download the product again, build and run.
