### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by egontier** [emonney/QuickApp#117]
Hello,

I'm looking carefully to your code and i think i'm going to use it for a new project. I have a few questions :

1- I can't find any test project on server and client side. Is this a part of QuickApp Pro ?
2- If you are using EF, why would you set up a repository / unit of work pattern, this doesn't make sense for me.

Thank you for your answers.

**Comment by karstenols** [comment]
Hi Egontier. There are a few tests of the angular application (Client side), which you can find in the folder: src\QuickApp\ClientApp\e2e\
I am not aware of any tests of the .net application (Server side), but I imagine that tests will be most welcome as a contribution...
