### ISSUE TITLE
Typescript errors on demo load

### ISSUE THREAD

**Issue by CD1010** [emonney/QuickApp#12]
I get these errors launching project as is in VS 2017.
I upgraded VS 2017
Tried updating all versions using npm check updates. 

ERROR in [at-loader] ./node_modules/rxjs/Subject.d.ts:16:22 
    TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
ERROR in [at-loader] ./node_modules/rxjs/observable/dom/WebSocketSubject.d.ts:24:22 
    TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.

**Comment by ayuceman** [comment]
I am facing the same error, any solution to this, tried npm update and updated typescript as well?

**Comment by CD1010** [comment]
I have typescript 2.2. No luck  with npm update

**Comment by waqarhabib** [comment]
In package.json file change  "typescript": "2.3.4",  
It work for me

**Comment by waqarhabib** [comment]
Also to get updated version of  typescript you can change it  to 
In package.json file change "typescript": "^2.4.1",
It also works

**Comment by ayuceman** [comment]
Added  "noStrictGenericChecks":  true to the tsconfig compiler options and it worked for me.

**Comment by CD1010** [comment]
I ended up changing the typescript : ^2.4.1 and setting noStrictGenericChecks: true.  
It was the generic checks, as version alone did not help me.
Thanks for the help

**Comment by emonney** [comment]
Typescript 2.4.0 works fine. I'll stick to this version until RxJs fixes it.
package.json now uses strict versions (no carets). This is to prevent updates such as this from breaking the template
