### ISSUE TITLE
This server only accepts HTTPS requests

### ISSUE THREAD

**Issue by yimseknyCorarl** [emonney/QuickApp#122]
Hello all, I try to publish it to IIS and it work but cannot login it shows message

`Severity: "error", 
Summary: "Unable to login", 
Detail: "This server only accepts HTTPS requests.", 
Error: "{
	"headers":{
		"normalizedNames":{},
		"lazyUpdate":null
	},
	"status":400,
	"statusText":"Bad Request",
	"url":"http://localhost:81/connect/token",
	"ok":false,
	"name":"HttpErrorResponse",
	"message":"Http failure response for http://localhost:81/connect/token: 400 Bad Request",
	"error":{
		"error":"invalid_request",
		"error_description":"This server only accepts HTTPS requests."
	}
}"`

![image](https://user-images.githubusercontent.com/25809685/49915654-3839e500-fec9-11e8-9f49-4c83d8195a42.png)

Thank for help this in advances.

**Comment by Mynken** [comment]
@yimseknyCorarl try to navigate to add "s" to http;
Old: http;//localhost:4200;
New: https;//localhost:4200;

If you can`t naviget to this page then you should check IIS or in VS is "https" enabled for your project.

**Comment by yimseknyCorarl** [comment]
Thank @Mynken for your answer, but I already change to use another template already, because I spent a lot of time with it already, :)

**Comment by Mynken** [comment]
> Thank @Mynken for your answer, but I already change to use another template already, because I spent a lot of time with it already, :)

@yimseknyCorarl 
Please provide link for template, which you are using.

**Comment by emonney** [comment]
Https requirement is highly recommended in production. You can however disable it from **Startup.cs** file during development.
Search for and comment out the below code: `app.UseHttpsRedirection();`

Also make sure "https" requirement is disabled in openiddict config: ` options.DisableHttpsRequirement();`
Openiddict code block below:
<pre><code>
.AddServer(options =>
                {
                    options.UseMvc();
                    options.EnableTokenEndpoint("/connect/token");
                    options.AllowPasswordFlow();
                    options.AllowRefreshTokenFlow();
                    options.AcceptAnonymousClients();
                    options.DisableHttpsRequirement(); // Note: Comment this out in production
                    options.RegisterScopes(
                        OpenIdConnectConstants.Scopes.OpenId,
                        OpenIdConnectConstants.Scopes.Email,
                        OpenIdConnectConstants.Scopes.Phone,
                        OpenIdConnectConstants.Scopes.Profile,
                        OpenIdConnectConstants.Scopes.OfflineAccess,
                        OpenIddictConstants.Scopes.Roles);

                    // options.UseRollingTokens(); //Uncomment to renew refresh tokens on every refreshToken request
                    // Note: to use JWT access tokens instead of the default encrypted format, the following lines are required:
                    // options.UseJsonWebTokens();
                })
</pre></code>
