### ISSUE TITLE
Grid Layout alignment

### ISSUE THREAD

**Issue by elrenatom** [emonney/QuickApp#123]
Hello,
I was navigate in the applicattion and verify this problem. In my opinion this grid needs to be align.

![bug layout](https://user-images.githubusercontent.com/15670639/50167976-7f611500-02d1-11e9-92d8-2d98adfa357f.png)

**Comment by emonney** [comment]
What do you mean by aligned? I did a test and I can't find the alignment issue you talk of.
Please clarify your request.

Closing for now. Reopen this issue when you provide more information
