### ISSUE TITLE
ERROR in error TS1149

### ISSUE THREAD

**Issue by chaldon** [emonney/QuickApp#128]
Trying to run app on Mac right after checkout. Got:

ERROR in error TS1149: File name '<path to project>/QuickApp/src/QuickApp/ClientApp/src/app/services/db-keys.ts' differs from already included file name '<path to project>/QuickApp/src/QuickApp/ClientApp/src/app/services/db-Keys.ts' only in casing.

The problem is in 2 files - auth.service.ts and configration.service.ts
Replacing rows
import { DBkeys } from './db-Keys';
to
import { DBkeys } from './db-keys';
fix the problem.

**Comment by emonney** [comment]
Fixed in dcc2fba83f751648f31d5f84ebc772ae8e4512ad 
Thanks for reporting
