### ISSUE TITLE
Why is CUSTOMER screen not using the customer data ? 

### ISSUE THREAD

**Issue by punkouter2021** [emonney/QuickApp#130]
And instead using the todo component ?  I would think you would want to use the Customer as a sample CRUD screen

**Comment by Mynken** [comment]
> And instead using the todo component ? I would think you would want to use the Customer as a sample CRUD screen

There is no CRUD for Customers and Products.

**Comment by adamdsouza1** [comment]
@punkouter2018 yes! was thinking the same!. If QuickApp had CRUD for atleast one among Customers or Products from the database it would have really been worth purchasing it. I purchased the pro version thinking it had it, being in newbie in angular i am finding it difficult to leverage the code to other modules. :(

**Comment by punkouter2018** [comment]
I just focusing on mvc and soon blazor..I'd rather skip over learned js and
angular
