### ISSUE TITLE
Error in the first execution

### ISSUE THREAD

**Issue by carlosarcos** [emonney/QuickApp#131]
[2019-04-25T18_04_40_590Z-debug.log](https://github.com/emonney/QuickApp/files/3118292/2019-04-25T18_04_40_590Z-debug.log)
After creating a new project with the template, installed in VS 2019, I launch the execution and it shows me this error:

An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:613

throw err;
^

Error: Cannot find module 'C:\DESARROLLO\Angular_NET_Core\Plantilla\Plantilla\Plantilla\ClientApp\node_modules\node-sass\bin\node-sass'

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
at Function.Module._load (internal/modules/cjs/loader.js:526:27)
at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! quickapp@2.7.2 theme: `node-sass --watch src/app/assets/themes/ --output src/assets/themes/ --output-style=compressed`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the quickapp@2.7.2 theme script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2019-04-25T18_04_40_590Z-debug.log](https://github.com/emonney/QuickApp/files/3118290/2019-04-25T18_04_40_590Z-debug.log)

**Comment by Mynken** [comment]
> [2019-04-25T18_04_40_590Z-debug.log](https://github.com/emonney/QuickApp/files/3118292/2019-04-25T18_04_40_590Z-debug.log)
> After creating a new project with the template, installed in VS 2019, I launch the execution and it shows me this error:
> 
> An unhandled exception occurred while processing the request.
> AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: internal/modules/cjs/loader.js:613
> 
> throw err;
> ^
> 
> Error: Cannot find module 'C:\DESARROLLO\Angular_NET_Core\Plantilla\Plantilla\Plantilla\ClientApp\node_modules\node-sass\bin\node-sass'
> 
> at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
> at Function.Module._load (internal/modules/cjs/loader.js:526:27)
> at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
> at internal/main/run_main_module.js:17:11
> npm ERR! code ELIFECYCLE
> 
> npm ERR! errno 1
> 
> npm ERR! quickapp@2.7.2 theme: `node-sass --watch src/app/assets/themes/ --output src/assets/themes/ --output-style=compressed`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the quickapp@2.7.2 theme script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [2019-04-25T18_04_40_590Z-debug.log](https://github.com/emonney/QuickApp/files/3118290/2019-04-25T18_04_40_590Z-debug.log)

Go to folder "ClientApp" and open it with console(VS Code, etc.) 
Type here: "npm i".
And if any errors exsist pleae paste them here. 
If all will be OK, just type "npm audit fix".
