### ISSUE TITLE
Load Error, Unable to retrieve user data from the server

### ISSUE THREAD

**Issue by shn2016** [emonney/QuickApp#134]
Hi All,

I'm having a load error while trying the preference panels.

the error shows that 
UriFormatException: Invalid URI: Invalid port specified.

and switching the user and role have similar issue.

Getting api with:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Does anyone has any idea about it ?

Many thanks

**Comment by Mynken** [comment]
> Hi All,
> 
> I'm having a load error while trying the preference panels.
> 
> the error shows that
> UriFormatException: Invalid URI: Invalid port specified.
> 
> and switching the user and role have similar issue.
> 
> Getting api with:
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> 
> Does anyone has any idea about it ?
> 
> Many thanks

Smth bad with your backend or just wrong port to call it.
