### ISSUE TITLE
npm install fail at QuickApp Pro 2.7.2

### ISSUE THREAD

**Issue by AllPIM** [emonney/QuickApp#137]
Hi, All
1. install nvm and install node.js v10.16.0, npm v6.9.0
2. run "dotnet restore" 
3. run "npm install" & "npm audit fix"
4. run "npm list" show below error

npm ERR! peer dep missing: @angular/common@^6.0.0-rc.0 || ^6.0.0, required by ngx-toasta@0.1.0

npm ERR! peer dep missing: @angular/compiler-cli@^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9, required by @angular-devkit/build-angular@0.801.0

npm ERR! peer dep missing: @angular/core@^6.0.0-rc.0 || ^6.0.0, required by ngx-toasta@0.1.0

npm ERR! peer dep missing: @angular/compiler-cli@^8.0.0-beta.0 || ^8.1.0-beta.0 || ^8.2.0-beta.0 || ^8.3.0-beta.0 || ^8.4.0-beta.0 || >=9.0.0-beta < 9, required by @ngtools/webpack@8.1.0

npm ERR! peer dep missing: typescript@>=3.4 < 3.5, required by @ngtools/webpack@8.1.0

**Comment by ameurm** [comment]
I got the same errors
