### ISSUE TITLE
Exception InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.

### ISSUE THREAD

**Issue by IngoManthey** [emonney/QuickApp#143]
When I open the user I get the following exception.
 InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.

As applicationUrl I have https: //localhost: 44350 registered.
In the ConfigureServices I have at services.AddAuthentication
options.RequireHttpsMetadata = true;

What can I do?

**Comment by andgest** [comment]
Hello,

You seem to have the same problem as me. => https://github.com/emonney/QuickApp/issues/150
Did you find a solution ?

Thank you in advance :)
