### ISSUE TITLE
QuickApp ASP.NET Core 3.0 / Angular 8 is no longer running under iis

### ISSUE THREAD

**Issue by RalfPreuss** [emonney/QuickApp#146]
The latest version 3.0 does not run under IIS.
First error: package.json not found.
Next: The command "run-p" is either misspelled or could not be found.

IIS V10
NodeJs 10.16.3
DotNetCore 3 Runtime

**Comment by IngoManthey** [comment]
Hi,
I also had a problem with the IIS.
