### ISSUE TITLE
[QuickApp Total Pack][ASP.NET 3.0] Microsoft.AspNetCore.SpaServices Error/Fail

### ISSUE THREAD

**Issue by d3wF1nk** [emonney/QuickApp#147]
1 `dotnet restore` in root directory
2 `npm install` in ClientApp directory
3 `File -> Open -> Project/Solution` with **Visual Studio 2019**
4 Run it with IIS Express

In logs appear this error:

```
Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 0% compiling

Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 10% building 0/0 modules 0 active 

Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 10% building 0/1 modules 1 active multi C:\Users\Utente\workALC\ExperimentalProjects\QuickApp.Pro\QuickApp\ClientApp\node_modules\webpack-dev-server\client\index.js?http://0.0.0.0:0/sockjs-node&sockPath=/sockjs-node C:\Users\Utente\workALC\ExperimentalProjects\QuickApp.Pro\QuickApp\ClientApp\src\main.ts

Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 10% building 1/1 modules 0 active 

Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 10% building 1/1 modules 0 active 

Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 10% building 1/2 modules 1 active multi C:\Users\Utente\workALC\ExperimentalProjects\QuickApp.Pro\QuickApp\ClientApp\src\polyfills.ts C:\Users\Utente\workALC\ExperimentalProjects\QuickApp.Pro\QuickApp\ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\jit-polyfills.js

Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 10% building 2/2 modules 0 active 
<s> [webpack.Progress] 10% building 2/2 modules 0 active 
<s> [webpack.Progress] 10% building 2/3 modules 1 active multi C:\Users\Utente\workALC\ExperimentalProjects\QuickApp.Pro\QuickApp\ClientApp\src\styles.scss
<s> [webpack.Progress] 10% building 3/3 modules 0 active 
<s> [webpack.Progress] 10% building 3/4 modules 1 active C:\Users\Utente\workALC\ExperimentalProjects\QuickApp.Pro\QuickApp\ClientApp\node_modules\webpack-dev-server\client\index.js?http://0.0.0.0:0/sockjs-node&sockPath=/sockjs-node

Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 10% building 4/4 modules 0 active 
```
And it continue until 100% building ...

```
Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 94% after asset optimization
<s> [webpack.Progress] 94% after seal
<s> [webpack.Progress] 94% after seal SuppressExtractedTextChunks
<s> [webpack.Progress] 95% emitting
<s> [webpack.Progress] 95% emitting CopyPlugin
<s> [webpack.Progress] 95% emitting index-html-webpack-plugin

Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 98% after emitting

Microsoft.AspNetCore.SpaServices: Error: <s> [webpack.Progress] 98% after emitting CopyPlugin
```

The application seems to works fine.
**Same issue with the Pro version also.**

**Comment by mrjohnr** [comment]
I have the same problem.posted also [here ](https://stackoverflow.com/questions/58073880/update-angular-devkit-and-got-fail-microsoft-aspnetcore-spaservices0)

**Comment by myalsailamy** [comment]
1) open this path (QuickApp/QuickApp/ClientApp/) in cmd or terminal 
2) write this command (ng serve -o) 
if it work that means no problems with angular packages .

**Comment by JernejHabjan** [comment]
Same problem

**Comment by JernejHabjan** [comment]
Update - I think this is normal behavior, as it is reported also by generic angular project, generated with dotnet CLI
`dotnet new angular -o my-new-app`
In angular.json file, property progress exists, which is turned to false in my-new-app. 
![image](https://user-images.githubusercontent.com/21958321/73056319-0ac2b780-3e8f-11ea-84a8-d900d0829b0f.png)
After turning it to true, it starts showing errors in console:
![image](https://user-images.githubusercontent.com/21958321/73056385-304fc100-3e8f-11ea-82e7-e25707d38953.png)

So I think this is normal behavior. If it bothers you, you can set it to false, and errors wont be shown.
Can anyone confirm if this is correct?

**Comment by lackovic** [comment]
I had the same problem, when running `dotnet run` I got lots of errors like the followings:
```
fail: Microsoft.AspNetCore.SpaServices[0]
      Compiling @angular/core : module as esm5
...
fail: Microsoft.AspNetCore.SpaServices[0]
      <s> [webpack.Progress] 10% building 1/1 modules 0 active
```

Despite the errors everything worked fine when running the web app.

`ng serve` did not show any error.

The errors disappeared after removing `"progress": true,` from `angular.json` like suggested by @JernejHabjan.

I don't think this behavior is "normal": the word _**FAIL**_ seems to indicates something is wrong on the .NET Core side.

```powershell
$ npm --version
6.14.4
```

```powershell
$ node --version
v14.2.0
```

```powershell
dotnet --info
Version:   3.1.202
```
