### ISSUE TITLE
The User/Role Management page never shows

### ISSUE THREAD

**Issue by jsnhsu** [emonney/QuickApp#148]
I'm using VS 2019 16.3.6.  No matter I clone the project here or use the template got from vs extention, the page of users/roles management page never show and I can see the bunch of errors like #147 mentioned.

And it keep showing the error like:
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
fail: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]
      IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
S

Is it related to the asptnet core version or your sample is good in the other  commercial bundle?

**Comment by tonydrake** [comment]
same here - running the core2.2 std/pro without issues (well minor, which I logged here), but core 3.0... no luck (so far)...

add the following to your stardup to see the message:
```
using Microsoft.IdentityModel.Logging;

     public void ConfigureServices(IServiceCollection services)
        {
            IdentityModelEventSource.ShowPII = true; //To show detail of error and see the problem 
```        
..
when I do that, I get:

```
set AlwaysIncludeUserClaimsInIdToken on the client configuration.
dbug: IdentityServer4.Endpoints.TokenEndpoint[0]
      Token request success.
fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
      Exception occurred while processing message.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://localhost:5055/.well-known/openid-configuration'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
fail: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]
```

I will post if I crack this  - let us know how you go... (I'm trying both STD and PRO as I use both templates)

**Comment by tonydrake** [comment]
OK.. went back to the original download files, and restarted - both STD/PRO is working WHEN you use IIS Express FIRST - this triggers a security alert to use the SSL development cert, which I accepted... 
i CANNOT get it to run as a QuckApp hosted app - and you know, I'm OK with that...  Maybe someone can work our what we need to do, but for me, I can run Ang 8 + core 3 which is a win/win and enough for me to migrate my apps to the new base....

**Comment by jsnhsu** [comment]
After read tony's reply I kind of feeling the issue is an environment related one, since I'm starting QuickApp in VS instead of IIS Express.  So I brought up the properties page of QuickApp and switch to Debug sheet and modify the App URL at bottom to "https://localhost:44350;http://localhost:5050".  If the ports varies, please open launchSettings.json and you'd see yours.  Okay, I can see users/roles management page now.  So it's working in my box as well.

FYI, I'm just git clone the QuickApp.git here and modify no code.

**Comment by emonney** [comment]
If this is still an issue please post your support topics at the forums: https://www.ebenmonney.com/support/product-support
