### ISSUE TITLE
Publishing to azure

### ISSUE THREAD

**Issue by Lobonator** [emonney/QuickApp#15]
Hi, thanks a lot for this template it is really cool. Do you have issues when publishing to azure from VS 2017? VS does not detect any databases in the project so I guess when I try to uploading to azure it doesnt link database of this project to my newly created database. Do you any suggestions for me? Thanks in advance.

**Comment by nkada** [comment]
After publishing to Azure, add a App Setting with key = Data:DefaultConnection:ConnectionString and set the database connection string as value.

**Comment by emonney** [comment]
@Lobonator see @nkada  comment for the solution. You have to do this configuration with Azure

**Comment by emonney** [comment]
Also you can change the connection string from "Data:DefaultConnection:ConnectionString" to "Data:DefaultConnection:ConnectionString" (Make sure you update all references).
This format will be recognized by Azure. Future versions will use this format.
