### ISSUE TITLE
The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request

### ISSUE THREAD

**Issue by Moalpima** [emonney/QuickApp#153]
Hi,

when I set ASPNETCORE_ENVIRONMENT to "Production" and start it for test purpose in VS I got following error:

The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

Any ideas?

**Comment by IngoManthey** [comment]
If you run the side on IIS look in the web.config:
`<aspNetCore processPath="dotnet" arguments=".\TipWeb.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" startupTimeLimit="3600" requestTimeout="23:00:00" hostingModel="inprocess">
      <environmentVariables>
        <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Production" />
      </environmentVariables>
    </aspNetCore>`
