### ISSUE TITLE
The app is stuck in loading page

### ISSUE THREAD

**Issue by xiaofeizhu1** [emonney/QuickApp#16]
I use visual studio 2017

**Comment by zuko623** [comment]
Open the console in your browser, the error you should be showing there.

**Comment by emonney** [comment]
What errors are you getting? You should see this from the browser's console as @zuko623 suggested.

**Comment by emonney** [comment]
Closing issue since there's no context to work with.
Reopen and provide the necessary error messages if this is still a problem.

**Comment by binfask** [comment]
I am getting this error

main-client.js Failed to load resource: the server responded with a status of 404 (Not Found)
