### ISSUE TITLE
Error Migration when use command (Update-Database) 

### ISSUE THREAD

**Issue by omarabdelkefi123** [emonney/QuickApp#166]
Error Number:2714,State:6,Class:16
There is already an object named 'AppCustomers' in the database.

**Comment by HomeroLara** [comment]
facing the same issue.

**Comment by IngoManthey** [comment]
If the database exists, add-migration must be called first.

**Comment by aydenizdin** [comment]
DatabaseInitializer.SeedAsync() throws it even the schema exists.

 bool isCreated = await _context.Database.EnsureCreatedAsync().ConfigureAwait(false);

here isCreated become false even the schema exists.

**Comment by aydenizdin** [comment]
public async Task SeedAsync()
        {
            bool isCreated = await _context.Database.EnsureCreatedAsync().ConfigureAwait(false);

            if (isCreated == false)
            {
                await _context.Database.MigrateAsync().ConfigureAwait(false);
            }
            
            await SeedDefaultUsersAsync();
            await SeedDemoDataAsync();
        }
