### ISSUE TITLE
401 Auth error when clicking the setting icon after login when deploy to IIS

### ISSUE THREAD

**Issue by Reagang** [emonney/QuickApp#167]
I'm getting 401 error when after I login as Admin and click on setting icon.
It works fine on IIS express(running Visual studio) but not working when I try to run it on IIS to test.
I saw a lot of comments that mention Application Url and SSL port. I tried changing it but it's not working. 
 
![image](https://user-images.githubusercontent.com/6199551/95691823-7964c280-0c22-11eb-8ac9-841d9813b145.png)

![image](https://user-images.githubusercontent.com/6199551/95691817-66ea8900-0c22-11eb-9be9-2f2c6846c10f.png)

**Comment by Reagang** [comment]
I saw a lot of comments that mention Application Url and SSL port. I tried changing it but it's not working.

**Comment by Reagang** [comment]
This seems to be related to **IdentityServer4**.
`dbug: IdentityServer4.Endpoints.TokenEndpoint[0]
      Token request success.
fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
      Exception occurred while processing message.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://localhost:5055/.well-known/openid-configuration'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
fail: IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[0]`

**Comment by karkcoder** [comment]
can you post your launchsetting.json?

**Comment by Reagang** [comment]
> launchsetting.json

`{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iis": {
      "applicationUrl": "https://localhost:44350",
      "sslPort": 0
    },
    "iisExpress": {
      "applicationUrl": "http://localhost:5050",
      "sslPort": 44350
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "MyApp": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5002"
    }
  }
}`

**Comment by karkcoder** [comment]
I think you might have similar issue like this post
https://github.com/emonney/QuickApp/issues/150

Make sure the port on your launchssetting and appsetting match. That was how I fixed it.

**Comment by kmuthugtk** [comment]
Hi,

The same errors, i am facing. please guide me to solve. Here i attached the launchsetting.json and appsettings.json

launchsetting.json

{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:52488",
      "sslPort": 44310
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "GTK": {
      "commandName": "Project",
      "dotnetRunMessages": "true",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}

appsettings.json

{
  "ConnectionStrings": {
    "DefaultConnection": "Server=localhost;User ID=sa;Password=123;Database=QuickApp;"
  },

  //Note: In Production change this to your actual host
  "ApplicationUrl": "http://localhost:5000",
  "https_port": 5001, //Set this for https redirection (e.g. 443)
}

can you please give me the solve for this as soon as possible.

**Comment by thomas1008** [comment]
my freinsd.plz any solution for that?

**Comment by Mynken** [comment]
@thomas1008 Check ApplicationUrl in appsetting.json
