### ISSUE TITLE
MSSQL DB and Linux

### ISSUE THREAD

**Issue by birdinox** [emonney/QuickApp#17]
Hi.
Great template. Thank you for that.
I am wondering, is it possible to run it on a Linux machine, without buying an MS-SQL license?
From the connection string, it seems like the program connects to MSSQLLocalDB, so I guess I have to install MSSQL on my machine (which means I have to buy ms-sql server and install it on a Windows machine. Am I right ?).
Is it possible to make this project work with a free cross platform DB like postgresql or MongoDb ?

Thanks.

**Comment by Xarkam** [comment]
Hello @birdinox, actualy, MSSql is in public preview. I don't know the final licence terms.
I created an issue that explains how to use it with sqlite. (#19)
You can rely on it to fit it for use with postgresql.

For MongoDb, you can see https://github.com/crhairr/EntityFrameworkCore.MongoDb but I don't know how to modify QuickApp to use it.

**Comment by emonney** [comment]
No you don't need MSSQL. EFCore is cross-platform and works with other dbs.
Look at @Xarkam comments (#19) for how to do this with sqlite.

**Comment by emonney** [comment]
Closing issue.
