### ISSUE TITLE
Will this project still be maintained?

### ISSUE THREAD

**Issue by IngoManthey** [emonney/QuickApp#171]
There are now .Net5, Angular 10. Even the support page is no longer displayed.
Does anyone have any more information?

**Comment by tonydrake** [comment]
I've got both the std and pro, and will me managing the upgrade myself. I'm working on the IdentServer4 upgrade and Ang10... the last release was a great base (he finished the sing up user, and 3rd part - google etc) signup well enough as a good base  - I'm a small dev team and this has saved me months of work, but feel I'm right from here, as an upgrade would be a pain... so, hopefully you have the pro versions with the material UI and ID work.

**Comment by IngoManthey** [comment]
@tonydrake
Yes, I have the ultimate version and am also working on it.
The template also saved me a lot of work myself. I only asked because the conversion to .Net5.0 and Angular 11 is imminent. It would be very helpful if this template were also further developed. But it looks like Mr. Monney is no longer interested in this project.

**Comment by rcarrico** [comment]
Looks like it has been updated to .net 5 and angular 11 as of two weeks ago.
