### ISSUE TITLE
Not issues more of a help

### ISSUE THREAD

**Issue by farhadwahaj** [emonney/QuickApp#173]
Hi! I am using QuickApp to learn and i could not find any tutorials on how to get the dbcontext part working, I have connected to SQLServer but I need to create a controller and then get the data from my server. I see that DAL project has a DB context file, do I use that or  should i create a new DBcontext inside Quickapp project how should approach this problem.
My pragramming skills are limited so sorry for asking. I simple how to would be gr8 help. maybe QuickApp for Dummies like me.
All help is deeply appreciated thanx in advance.

regards
Farre

**Comment by IngoManthey** [comment]
Hi, 
you just have to adjust the connection string in appsettings.json.
For example:
```
"ConnectionStrings": {
    "DefaultConnection": "data source=ServerName;database=DatabaseName;user id=UserName;password=Password;MultipleActiveResultSets=true"
  },
```
Regards Ingo

**Comment by farhadwahaj** [comment]
Yes i have done that i need to make crud how to send and recieve data from
controller

Den sön 7 feb. 2021 12:29Ingo Manthey <notifications@github.com> skrev:

**Comment by Mynken** [comment]
@farhadwahaj Just learn the basics of asp net :)

**Comment by farhadwahaj** [comment]
Thats what i am doing, i need just one example with QuickApp.

Den fre 19 mars 2021 11:41Vladyslav Hrehul ***@***.***> skrev:

**Comment by Mynken** [comment]
@farhadwahaj example of how to work with controllers and send/receive data is not dependent on a project - it is general approach.
Just find some guide who to do this(or you can find how to work with unitOfWork)

**Comment by farhadwahaj** [comment]
I did follow some examples but did not work for me. Thats why i posted on
Quickapp. Have you used Quickapp?

Den fre 19 mars 2021 12:29Vladyslav Hrehul ***@***.***> skrev:

**Comment by Mynken** [comment]
@farhadwahaj All works Ok, without problems.
If you don`t know c# asp net mvc - then it is not an issues of QuickApp.
Please learn basics and delete this issue.
