### ISSUE TITLE
Invalid HTTP request for token endpoint - IdentityServer4 ASP.NET Core 3.1

### ISSUE THREAD

**Issue by kmuthugtk** [emonney/QuickApp#174]
![loZUt](https://user-images.githubusercontent.com/76728951/110210409-8bdee180-7ecc-11eb-8fcc-9730d89d6fa4.jpg)

The connect/token is working good by using swagger, but when I'm trying to use it in postman, an error is showing

{
 "error": "invalid_request"
}
The Status code: 400 Bad Request.

How to fix this issue?

**Comment by Mynken** [comment]
@kmuthugtk check the scope - maybe you are missing something here.
