### ISSUE TITLE
ERROR TypeError: Unable to get property 'share' of undefined or null reference

### ISSUE THREAD

**Issue by nkada** [emonney/QuickApp#18]
I get this error only in Microsoft Edge. 

![image](https://user-images.githubusercontent.com/1577989/28793885-64d76b54-762c-11e7-83b9-e060541fe2d3.png)

![image](https://user-images.githubusercontent.com/1577989/28793894-6a9ba2bc-762c-11e7-8914-25d1d6ca2869.png)

**Comment by emonney** [comment]
Tested in Microsoft Edge (Working!). 
Which version of VS, QuickApp, Edge are you using?
Also are you sure this is not coming from another package you added?

**Comment by emonney** [comment]
Closing. Feel free to reopen if this is still an issue.
