### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by dwilliams2006** [emonney/QuickApp#187]
Using the .net5/angular 11 version of the template

Running the app in Visual Studio/localhost I have no problem with the app.

I have published my app in IIS and I can get to home page no problem. As soon as I try to log in I get this message:

UNABLE TO LOGIN-

issuer must use HTTPS (with TLS), or config value for property 'requireHttps' must be set to 'false' and allow HTTP (without TLS).

I have tried all kinds of settings to make this go away and I cannot. I do not need SSL for this app because it is being served via  a reverse proxy through a DMZ.

Please help!!!! I really like this app and need to get past this so I can finish building out this site.

I commented out  app.UseHttpsRedirection();   This did not help.
I've made several attempts to modify the appsettings and launchSetting. Nothing has worked.

Thank you

**Comment by Mynken** [comment]
https://stackoverflow.com/questions/50935730/how-do-i-disable-https-in-asp-net-core-2-1-kestrel

**Comment by dwilliams2006** [comment]
Mynken, that doesn't work either.
No matter what I do it always comes up with the same error message:
UNABLE TO LOGIN-

issuer must use HTTPS (with TLS), or config value for property 'requireHttps' must be set to 'false' and allow HTTP (without TLS).
