### ISSUE TITLE
Using with Sqlite

### ISSUE THREAD

**Issue by Xarkam** [emonney/QuickApp#19]
I explain to use with SQlite.

1. Add reference `<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="1.1.2" />` in _QuickApp.csproj_, save and make a `dotnet restore`

2. Modiffy connectionString in _appsettings.json_ to `"ConnectionString": "Filename=./QuickApp.sqlite"` (give the filename if you want)

3. Open _Startup.cs_ and change the line 79 :
`options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"], b => b.MigrationsAssembly("QuickApp"));`
to
`options.UseSqlite(Configuration["Data:DefaultConnection:ConnectionString"], b => b.MigrationsAssembly("QuickApp"));`

4. Make a `dotnet ef database update`
A new fold named _Migrations_ is created with old file for SqlServer.

5. In QuickApp folder execute with `dotnet run`

**Comment by emonney** [comment]
Thanks for your linux input. I'll leave these comments open for now as a reference for others. Until I create a FAQ with some of these tips.

**Comment by emonney** [comment]
Marking as closed for now.
