### ISSUE TITLE
Can this program support NET6. 0 and above?

### ISSUE THREAD

**Issue by Pacteraed** [emonney/QuickApp#199]
When running with 5.0, its functions can be used normally, but when I switch to sdk6.0 The version of 0 is and the prompt cannot be run.

**Comment by tonydrake** [comment]
I upgraded to 6.0 without any issues manually - just needed to change the
target and away you go!.

**Comment by Pacteraed** [comment]
Thanks,Can you tell me what to do.
1. Change database to local database
![image](https://user-images.githubusercontent.com/96095876/155916279-93f58d94-341f-4230-99e4-0e2d364a1a52.png)
![image](https://user-images.githubusercontent.com/96095876/155916302-487c9c48-81ae-469a-85e3-9fe5460cdc5f.png)
2. Change target to 6.0
![image](https://user-images.githubusercontent.com/96095876/155916133-8a6c5524-c33e-4b3e-af09-cc1a2ae3ff83.png)
3.F5 Run QuickApp
Throw this exception：
![image](https://user-images.githubusercontent.com/96095876/155916416-9e3f1b9b-751f-433a-ba82-1f35318c50ce.png)

**Comment by Pacteraed** [comment]
Can you give me a migrated database file？

**Comment by Pacteraed** [comment]
OK, thank you. After I try again, it's OK. Thank you again!
