### ISSUE TITLE
why not @angular/cli  and @angular/material 

### ISSUE THREAD

**Issue by badre429** [emonney/QuickApp#2]
* Most of angular project   using @angular/cli can you explain why this porject is not using it 
* why not using @angular/material rather than bootstrap

**Comment by emonney** [comment]
@angular/cli: Angular cli is nice, it uses the command line, this gets you something similar without the command line
@angular/mateiral: Angular Material2 was in alpha when this project started, Itlacked core components used in this project. Bootstrap is matured and nice too. A material version will be created in the near future
