### ISSUE TITLE
Build main-client.js in Linux

### ISSUE THREAD

**Issue by Xarkam** [emonney/QuickApp#21]
If you are ready to run quickapp under linux (see #19 & #20), before execute, you need to build _main-client.js_ file.
For this, you need to execute two commands:
- `node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod `
- `node node_modules/webpack/bin/webpack.js --env.prod`

First command, generate the dist dir in wwwroot.
Second command, build the main-client.js file.

**Comment by emonney** [comment]
Yes, this will be done automatically if you use Visual Studio. Other test editors you need to run this manually.
Just `npm run dev-build` will suffice for dev purposes.
Use `node node_modules/webpack/bin/webpack.js --env.prod` do generate packages for production deployment

**Comment by emonney** [comment]
Closing the issue for now.
