### ISSUE TITLE
Get 401 when deploying on IIS

### ISSUE THREAD

**Issue by kfconeone** [emonney/QuickApp#214]
I've deployed the app on my IIS as a sub-application and had a hard time to configure the some settings, but finally I can login sucessfully, and the url is like:
[https://localhost/testapp/](url)

Then I go to the https://localhost/testapp/settings#preferences and https://localhost/testapp/settings#settings
I got bunch of 401 error:
![image](https://user-images.githubusercontent.com/25839543/202458132-830b229b-1c80-48bd-8473-7454f5f27273.png)

response header:
Bearer error="invalid_token"

then I check the Event Viewer and got this exception:
![image](https://user-images.githubusercontent.com/25839543/202458627-9b6c3b82-aab9-4aa4-bfdb-eda17a888e4c.png)

here is what I changed in appsettings.json
```json
{
  "AuthServerUrl": "https://localhost/testapp",
  "https_port": 443,
}
```
can  help me with that? Or maybe share some deployment guide to deploy on IIS as sub-application?

***updated***
after a few hours digging, I found out that even without being a sub-application, it still cannot work on IIS, so maybe I just need help about deploying on IIS.

I think maybe it's about IdentityServer4's configuration?

**Comment by emonney** [comment]
Hello,
This article should guide you to deploying asp.net core apps to IIS: [https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-6.0&tabs=visual-studio](url)

### In appsettings.json
- Make sure AuthServerUrl points to the host of your authorization server.
- DB ConnectionStrings is properly configured

### In web.config
- Make sure environment variables from testing is cleared. Should look something like this unless you have specific environment variables you wish to set
`    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" startupTimeLimit="3600" requestTimeout="23:00:00" hostingModel="inprocess">
      <environmentVariables />
    </aspNetCore>`

I'll recommend trying to deploy the unmodified application to IIS and get it working first. So you can isolate any of your changes that might be getting in the way

Regards.

**Comment by kfconeone** [comment]
Hi, @emonney , thanks for your reply,
I've been trying this for another two days and still the same, but when I deploy to Azure, it works perfectly, 
I just don't understand why I cannot deploy on IIS, maybe there is other problems like certifications?

Or can you deploy on localhost IIS with development certification without problems?

**Comment by emonney** [comment]
Let's see how your 'appsettings.json' and 'web.config' looks like. You can post them here or email them to support@ebenmonney.com.

Also are you able to publish the vanilla (unmodified) version of QuickApp to IIS?

**Comment by kfconeone** [comment]
I can deploy to IIS and login without problems, but the accessToken cannot
persist, then whenever I change page or refresh, I will get a bunch of 401
errors, then I check the network and find out the token I ask from the
server keep  changing.
I didn't even change any code inside the project, except the db connection
string and server location/port in appsettings.json.

If it's necessary I could provide my project to you.

Thanks for your reply.

Ebenezer Monney ***@***.***> 於 2022年12月21日 週三 下午10:36寫道：

**Comment by kfconeone** [comment]
Sorry to keep bothering you, I have successfully deploy the site on IIS
without SSL, but I cannot understand why ssl would cause this problem.

Currently it is fine by me without SSL, just a little qualm tbh🙂.

Thanks for your help.


Kevin GPie ***@***.***> 於 2022年12月22日 週四 上午10:30寫道：

**Comment by graygonzalez77** [comment]
> Currently it is fine by me without SSL, just a little qualm tbh🙂.

can you share how did fixed the problem

**Comment by emonney** [comment]
If this is still an issue please post your support topics at the forums: https://www.ebenmonney.com/support/product-support
