### ISSUE TITLE
Not able to run after successful build for VS 2015 . 

### ISSUE THREAD

**Issue by VinodParmar** [emonney/QuickApp#22]
This site can’t be reached

localhost refused to connect.
Search Google for localhost 50666
ERR_CONNECTION_REFUSED

Please help me.....

**Comment by emonney** [comment]
From package.json, change all  "package_name": "^x.y.z" to  "package_name": "x.y.z" (That is remove the carret "^" from the version). e.g. "jquery": "^3.2.1" will become "jquery": "3.2.1".
Do this for all dependencies in package.json.
This is only needed if you're using the VS 2015 version pending an update. VS 2017 version already uses this approach.
This will use the exact package versions rather than the newest minor version.
Let me know if this helps.

**Comment by VinodParmar** [comment]
Appreciate your quick response, But didn't work for me...Still getting the same issue.

**Comment by emonney** [comment]
What errors are you getting? You need to provide much context to your issue.
PLease provide the details of the error you're getting from the backend, as well as error's from the browser's console

**Comment by VinodParmar** [comment]
Hi Ebenezer Monney 

Thanks for your attention, Actually I am using VS2015 Professional with update 3.
PM> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)
Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

Getting issue after successful build…

1>------ Rebuild All started: Project: QuickApp, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: DAL, Configuration: Debug Any CPU ------
2>  C:\Program Files\dotnet\dotnet.exe build "C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickApp-VS.2015-Version-master\src\DAL" --configuration Debug --no-dependencies --no-incremental
2>  Project DAL (.NETStandard,Version=v1.6) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
2>  Compiling DAL for .NETStandard,Version=v1.6
2>  Compilation succeeded.
2>      0 Warning(s)
2>      0 Error(s)
2>  Time elapsed 00:00:51.1505294
2>   (The compilation time can be improved. Run "dotnet build --build-profile" for more information)
1>  C:\Program Files\dotnet\dotnet.exe build "C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickApp-VS.2015-Version-master\src\QuickApp" --configuration Debug --no-dependencies --no-incremental
1>  Project QuickApp (.NETCoreApp,Version=v1.1) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
1>  Compiling QuickApp for .NETCoreApp,Version=v1.1
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : module.js:471
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error :     throw err;
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error :     ^
1>DNX : error : Cannot find module 'C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickApp-VS.2015-Version-master\src\QuickApp\node_modules\webpack\bin\webpack.js'
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error :     at Function.Module._resolveFilename (module.js:469:15)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error :     at Function.Module._load (module.js:417:25)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error :     at Module.runMain (module.js:604:10)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error :     at run (bootstrap_node.js:394:7)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error :     at startup (bootstrap_node.js:149:9)
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error :     at bootstrap_node.js:509:3
1>  Compilation succeeded.
1>      0 Warning(s)
1>      0 Error(s)
1>  Time elapsed 00:01:01.9833588
1>   (The compilation time can be improved. Run "dotnet build --build-profile" for more information)
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

General output :
We were unable to automatically populate your Visual Studio Team Services accounts.
The following error was encountered: TF400813: Resource not available for anonymous access. Client authentication required.

Then run the project and get the following error.

This site can’t be reached
localhost refused to connect.
Search Google for localhost 50666
ERR_CONNECTION_REFUSED
I checked with all browser setting, which is fine…..and also made changes as you suggested in package.json

“package.json, change all "package_name": "^x.y.z" to "package_name": "x.y.z" (That is remove the carret "^" from the version). e.g. "jquery": "^3.2.1" will become "jquery": "3.2.1".


Please guide me in this red colored error during build.

**Comment by emonney** [comment]
From the line below  it appears you don't have Webpack properly installed.

"1>DNX : error : Cannot find module 'C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickApp-VS.2015-Version-master\src\QuickApp\node_modules\webpack\bin\webpack.js'"

Do the following: open command prompt at "C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickApp-VS.2015-Version-master\src\QuickApp" and run the following commands:
1. npm install
2. npm run dev-build

Make sure they all succeed.
Copy and paste the results from these command here if they still fail

**Comment by Xarkam** [comment]
You cannot update you .NET Core to 1.0.5 ?
In september, .NET Core 2.0 is launched certainly during the MS inovation summit.

**Comment by VinodParmar** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd..

C:\Windows>cd..

C:\>cd C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickApp-VS.2015
-Version-master\src\QuickApp

C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickApp-VS.2015-Versio
n-master\src\QuickApp>npm install
npm WARN deprecated ng2-bootstrap@1.3.3: DEPRECATED: package was renamed to ngx-
bootstrap

> node-sass@4.5.0 install C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-mast
er\QuickApp-VS.2015-Version-master\src\QuickApp\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Vinod\AppData\Roaming\npm-cache\node-sass\4.5.0\
win32-x64-48_binding.node

> node-sass@4.5.0 postinstall C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-
master\QuickApp-VS.2015-Version-master\src\QuickApp\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickAp
p-VS.2015-Version-master\src\QuickApp\node_modules\node-sass\vendor\win32-x64-48
\binding.node
Testing binary
Binary is fine
ng-quickapp@0.1.0 C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\Quick
App-VS.2015-Version-master\src\QuickApp
+-- @angular/platform-browser@2.4.8
+-- @angular/platform-browser-dynamic@2.4.8
+-- @angular/platform-server@2.4.8
+-- @angular/router@3.4.8
+-- @types/jquery@2.0.40
+-- @types/node@7.0.5
+-- UNMET PEER DEPENDENCY angular2-platform-node@2.1.0-rc.1
+-- aspnet-prerendering@2.0.3
+-- aspnet-webpack@1.0.28
| `-- es6-promise@3.3.1
+-- awesome-typescript-loader@3.0.0
+-- bootstrap-select@1.12.2
+-- UNMET PEER DEPENDENCY core-js@^2.4.0
+-- css-loader@0.26.2
+-- extract-text-webpack-plugin@2.0.0
+-- file-loader@0.10.0
+-- html-loader@0.4.4
+-- ng2-bootstrap@1.3.3
+-- ng2-charts@1.5.0
+-- node-sass@4.5.0
+-- UNMET PEER DEPENDENCY rxjs@5.2.0
+-- sass-loader@6.0.2
+-- typescript@2.2.1
+-- url-loader@0.5.8
+-- webpack@2.2.1
+-- webpack-hot-middleware@2.17.1
`-- UNMET PEER DEPENDENCY zone.js@0.7.7

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN @swimlane/ngx-datatable@6.3.0 requires a peer of core-js@^2.4.0 but non
e was installed.
npm WARN angular2-universal@2.1.0-rc.1 requires a peer of rxjs@~5.0.0-beta.12 bu
t none was installed.
npm WARN angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but no
ne was installed.
npm WARN angular2-universal-patch@0.2.1 requires a peer of angular2-platform-nod
e@^2.0.0 but none was installed.
npm WARN angular2-universal-polyfills@2.1.0-rc.1 requires a peer of zone.js@~0.6
.21 but none was installed.

C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickApp-VS.2015-Versio
n-master\src\QuickApp>npm run dev-build

> ng-quickapp@0.1.0 dev-build C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-
master\QuickApp-VS.2015-Version-master\src\QuickApp
> node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js

Hash: e6e733d5c0978acc38a9
Version: webpack 2.2.1
Child
    Hash: e6e733d5c0978acc38a9
    Time: 38928ms
                                   Asset     Size  Chunks                    Chu
nk Names
    674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
    912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]
    b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
    89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
                               vendor.js  4.92 MB       0  [emitted]  [big]  ven
dor
                              vendor.css   670 kB       0  [emitted]  [big]  ven
dor

C:\Users\Vinod\Downloads\QuickApp-VS.2015-Version-master\QuickApp-VS.2015-Versio
n-master\src\QuickApp>

**Comment by VinodParmar** [comment]
Companezer, Still facing same issue......

**Comment by Xarkam** [comment]
Have same error on my test. But I don''t have any more vs2015 for make compilation for testing.

**Comment by VinodParmar** [comment]
Debug Output :+1: 

The program '[6120] dotnet.exe' has exited with code -2147450749 (0x80008083).
The program '[8828] iisexpress.exe' has exited with code 0 (0x0).

Is this responsible for this issue? if yes then please suggest the way to get rid of it.

**Comment by VinodParmar** [comment]
Thanks, Companezer and Xarkam for your helps.

I was using the wrong .netcore version in project.json , causes error occurred

I replace in place of 

 "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.1.0-preview4-final",
      "type": "build"
    },

This (below) .

   "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },


Then Finally able to run and able to debug.............

Companezer, Can you please tell me about related sql db script for DB ?

**Comment by Xarkam** [comment]
Coo.

Open new issue for your question about the db :)

**Comment by emonney** [comment]
Great!.

**Comment by emonney** [comment]
Rather than downgrade your Microsoft.NETCore.App version you can update your .net sdk from here: https://www.microsoft.com/net/download/core
