### ISSUE TITLE
Using on VS 2015

### ISSUE THREAD

**Issue by Ros1991** [emonney/QuickApp#23]
Hello,
Is it possible to use this on VS 2015?

thanks
Rodrigo

**Comment by emonney** [comment]
Yes. See: https://github.com/emonney/QuickApp-VS.2015-Version

**Comment by Ros1991** [comment]
When i try to run, the website simply do not run... It seems that IIS could not start the webapp.

**Comment by Xarkam** [comment]
You don't have any message sayed with UNMET PEER DEPENDENCY ?

This is a Angular problem.

**Comment by VinodParmar** [comment]
Ros1991,

Please check your .netcoreapp version and update it on pakage .json.

Same issue was faced recently and finally get resolved by the ablve solution.

**Comment by emonney** [comment]
Do the following:
1. Update your .net skd: https://www.microsoft.com/net/download/core if you're using an older version
2. Replace all `"^` and `"~` in package.json with `"` to force download the specific versions of the client packages
3. Run `npm install` to refresh the client packages
4. Run `npm run dev-build` to rebuild the client packages

If you still have errors:
1. Post your error logs here
2. Run `dotnet --info` and paste the results here
