### ISSUE TITLE
.NET CORE 2

### ISSUE THREAD

**Issue by hosseinjalili** [emonney/QuickApp#25]
Hi
Do you have any plan for upgrading this project to .NET Core 2.0?
please have a plan :)

regards

**Comment by emonney** [comment]
Yes, the next update will be based on .netcore 2.0. That should happen before close of this month.
Follow me on twitter to learn when it's available: https://twitter.com/kommand

**Comment by emonney** [comment]
This repository was updated to .netcore 2.0. Do a pull to get the latest bits.

**Comment by hosseinjalili** [comment]
Thanks
