### ISSUE TITLE
Seperate Angular & WebAPI

### ISSUE THREAD

**Issue by aredfox** [emonney/QuickApp#27]
Wouldn't it be better to seperate the Angular app in a seperate project structure from the WebAPI project? That way the WebAPI project isn't as involved with the Angular specifics, because one might use the WebAPI for more than one front facing website. 

It could also be a nice example on how to use JWT that way for angular or react (or vue..) clients.

**Comment by emonney** [comment]
If you prefer just the WebAPI I believe you can do so by simply deleting the ClientApp folder. Have you had any issues using this approach?

Is there any particular reason to prefer JWT tokens? [See here on how to access idToken from the client side](https://github.com/emonney/QuickApp/blob/fb192526bb509336a890b94565b3ac716727b6a6/src/QuickApp/ClientApp/app/services/auth.service.ts#L130)
