### ISSUE TITLE
Version Incompatibilities

### ISSUE THREAD

**Issue by wmlockhart** [emonney/QuickApp#28]
I am having a problem getting the solution to build. Could you help me please. I had to upgrade my version of Visual Studio to 15.3.4 to overcome a number of issues about a missing reference to assembly 'netstandard, Version=2.0'.

However, the problems I now have are:

Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)

The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0. DAL C:\Program Files\dotnet\sdk\1.1.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	126	

The current .NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0. QuickApp C:\Program Files\dotnet\sdk\1.1.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	112	

How can I resolve these issues?

Thanks.

Walter

**Comment by emonney** [comment]
Do you have a project in your solution that still targets .netcore 1.0? Make sure all the project references are built on the 2.0 sdk.
You can update your solution from this repository which was also updated to 2.0.

**Comment by wmlockhart** [comment]
Thanks emonney. All that I've done is copy down this repository. In what files will I find the references that I must change?

**Comment by emonney** [comment]
This is a diff of the two commits: https://github.com/emonney/QuickApp/compare/6caae398cd196e61d0facd61008aa299c0d7979b...fb192526bb509336a890b94565b3ac716727b6a6

**Comment by wmlockhart** [comment]
Thank you. I'll take a look.

**Comment by marcelo-maciel** [comment]
@wmlockhart i have the same issue...

**Comment by marcelo-maciel** [comment]
@wmlockhart  and @emonney , i found the solution.
@wmlockhart , download and install the SDK: https://www.microsoft.com/net/core#windowscmd
Open VS2017 and all dependencias automatically will be downloaded.

**Comment by wmlockhart** [comment]
@marcelo-maciel thank you so much. This worked for me too.
@emonney Wow! This is an awesome template. Thank you. Have you plans for any further development?

**Comment by emonney** [comment]
@marcelo-maciel Yes. Look out for more features. PR to improvements and features found in common applications are also welcomed
