### ISSUE TITLE
Build Webpack fails

### ISSUE THREAD

**Issue by JakobSnow** [emonney/QuickApp#29]
Hi,

I'm new in trying to use this repository. When I try to build the latest version with Visual Studio 2017, .net core 2.0, the build of webpack fails.

> 6777 verbose stack Error: The package webpack does not satisfy its siblings' peerDependencies requirements!
6777 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\install.js:125:32
6777 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\install.js:264:7
6777 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:138:5
6777 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:251:14
6777 verbose stack     at cb (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
6777 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:251:14
6777 verbose stack     at cb (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
6777 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:251:14
6777 verbose stack     at cb (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
6777 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:251:14
6778 verbose cwd C:\Users\jh040194\Source\Repos\QuickApp\src\QuickApp
6779 error Windows_NT 6.1.7601
6780 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
6781 error node v0.12.2
6782 error npm  v2.7.4
6783 error code EPEERINVALID
6784 error peerinvalid The package webpack does not satisfy its siblings' peerDependencies requirements!
6784 error peerinvalid Peer @ngtools/webpack@1.7.1 wants webpack@^2.2.0 || ^3.0.0
6784 error peerinvalid Peer aspnet-webpack@2.0.1 wants webpack@^1.13.2 || ^2.1.0-beta
6784 error peerinvalid Peer extract-text-webpack-plugin@3.0.0 wants webpack@^3.1.0
6784 error peerinvalid Peer sass-loader@6.0.6 wants webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0
6784 error peerinvalid Peer karma-webpack@2.0.4 wants webpack@^1.0.0 || ^2.0.0 || ^3.0.0
6784 error peerinvalid Peer webpack-dev-middleware@1.12.0 wants webpack@^1.0.0 || ^2.0.0 || ^3.0.0
6784 error peerinvalid Peer uglifyjs-webpack-plugin@0.4.6 wants webpack@^1.9 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3.0.0
6785 verbose exit [ 1, true 

Also I've tried this ` node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js` directly.
Then I'll got this answer:

> C:\Users\jh040194\Documents\Visual Studio 2017\Projects\QuickApp-2.0\src\QuickAp
> p\node_modules\webpack\bin\webpack.js:152
> yargs.parse(process.argv.slice(2), (err, argv, output) => {
>                                                        ^^
> SyntaxError: Unexpected token =>
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:501:10)
>     at startup (node.js:129:16)
>     at node.js:814:3

Any advise or help?
And by the way, I've tried everything mentioned in the "Installation Notes".
Regards,
Jakob

**Comment by zouzou73** [comment]
It looks like you're running an older version of node.js and npm.
Try updating node and npm to the latest version

**Comment by JakobSnow** [comment]
Thanks, that was my problem! :+1:
