### ISSUE TITLE
Visual Studio 2017 template error. Unexpected dependency 'OpenIddict' with no version number.

### ISSUE THREAD

**Issue by CybrZr00** [emonney/QuickApp#3]
Sadly this is not working with Visual Studio 2017 using the template.

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'OpenIddict.EntityFrameworkCore (>= 1.0.0-beta2-0560)' for '.NETStandard,Version=v1.6'.				
Error		Unable to resolve 'OpenIddict.EntityFrameworkCore (>= 1.0.0-beta2-0560)' for '.NETCoreApp,Version=v1.1'.				
Error		Unable to resolve 'OpenIddict (>= 1.0.0-beta2-0560)' for '.NETStandard,Version=v1.6'.				
Error		Unable to resolve 'OpenIddict (>= 1.0.0-beta2-0560)' for '.NETCoreApp,Version=v1.1'.				
Error		Unable to resolve 'OpenIddict.Mvc (>= 1.0.0-beta2-0560)' for '.NETCoreApp,Version=v1.1'.				
Error		Unexpected dependency 'OpenIddict' with no version number.	QuickApp (loading...)	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'OpenIddict.EntityFrameworkCore' with no version number.	QuickApp (loading...)	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
`

**Comment by CybrZr00** [comment]
Fixed: Add "https://www.myget.org/F/aspnet-contrib/api/v3/index.json" to your nuget sources, and fix for Dropdow error is just to edit the app.module.ts and change DropdownModule to BsDropdownModule

**Comment by emonney** [comment]
Glad you got it fixed.

Add this file [NuGet.config](https://github.com/emonney/QuickApp/raw/9b122b7f3c38121699d3ec41b700474e192abe37/src/QuickApp/NuGet.config) to the "solution folder" (i.e the folder containing the solution file: QuickApp.sln). This contains the packageSources for OpenIddict and will ensure visual studio always knows where to download the nuget packages from.

[Use this: VisualStudio 2017 QuickApp Extension from the marketplace. Don't forget to rate/star](https://marketplace.visualstudio.com/items?itemName=adentum.QuickApp-ASPNETCoreAngularXProjectTemplate)
