### ISSUE TITLE
Web Api not running

### ISSUE THREAD

**Issue by marcelo-maciel** [emonney/QuickApp#31]
@emonney, can i change the message and behavior of the login component when backend service is not running?

Today behavior:
Show a dialog with a message:
Dear Developer! It appears your backend Web API service is not running...Would you want to temporarily switch to the online Demo API below?(Or specify another) .
And enable to change the API url

Suggested behavior:
Show an alert with a message:
"Dear user, it looks like the system is temporarily offline. Please try again later or contact your system administrator."

**Comment by emonney** [comment]
Test if it's localhost. If not show "Dear User dialog"

**Comment by marcelo-maciel** [comment]
No, no. Today are fine showing the dialog, but thinking in production code, show the change web api dialog to a final user is a mistake.
Can i transform it to an "alert dialog", and remove the new URL input?

**Comment by emonney** [comment]
Production user's won't see that dialog. Only users browsing from localhost
will.
I added that to give user's the opportunity to test the Angular part
without the asp backend my specifying their own backend.

On 22 September 2017 at 13:23, Marcelo Mohr Maciel <notifications@github.com

**Comment by marcelo-maciel** [comment]
Nice, I have not seen it! How can i change to production?
I tried change degug/release on VS, but the dialog about api keeps appearing.

**Comment by marcelo-maciel** [comment]
Nice! Ok, I will change the text.

**Comment by Sami-L** [comment]
@emonney, What if I would like to use localhost to host the backend, how to get rid of that message of "Dear Developer ..." ?
