### ISSUE TITLE
Accepting PR's ? want localization?

### ISSUE THREAD

**Issue by rmarinho** [emonney/QuickApp#33]
Thinking in adding localization all around, what do you think?

**Comment by marcelo-maciel** [comment]
Hi @rmarinho!

I added a PR with PT-BR, but is not complete, because there are many hardcoded strings.

**Comment by marcelo-maciel** [comment]
This would be great @rmarinho

**Comment by emonney** [comment]
The aim is to keep the template as simple as possible, with enough pointers for devs to build on top quickly.
I think there's enough pointers for devs to add additional localisations as they see fit. All round localization will not be beneficial to all.
