### ISSUE TITLE
Difficulty connecting to local database

### ISSUE THREAD

**Issue by MarkStega** [emonney/QuickApp#39]
If I clone the repository and then do the build from the command per the ReadMe when I execute with "dotnet run" I get a failure of "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or not accessible". Ihave SQL Server 2017 installed on a Windows 10 64 bit system and the local database option was included in the installation.

If I edit appsettings.json and change the server definition from "(local)" to "localhost\\SQLExpress" and do another "dotnet run" then the database is created and tables appear to be correctly populated.

If I then stop the running session and open the solution in VS2017 and do CTRL-F5 then there is an issue connecting to the database. I've attached the console log messages.
[localhost-1508956499918.log](https://github.com/emonney/QuickApp/files/1415760/localhost-1508956499918.log)

Any thoughts on the second issue which is not getting successfully connected to the database using a trusted connection?

**Comment by wmlockhart** [comment]
I also have SQL Server 2017 installed on my local development machine.

In both appsettings.json and appsettings.Development.json I have the following configuration settings:

  "ConnectionStrings": {
    "DefaultConnection": "Server=GENEVA;Database=EHC;Trusted_Connection=True;MultipleActiveResultSets=true"
  },

I would suggest that the same settings exist in both .json files.

**Comment by MarkStega** [comment]
That was the issue - I hadn't updated the appsettings.development.json
