### ISSUE TITLE
How can I run this template on MySQL database?

### ISSUE THREAD

**Issue by eng-mohammed-emam** [emonney/QuickApp#41]
How can I run this template with MySQL database?

**Comment by emonney** [comment]
Check here for guide on using different db providers: https://docs.microsoft.com/en-us/ef/core/providers/mysql/

**Comment by LeiYangGH** [comment]
I think the code is highly tied to sqlserver, such as `datetime2` `nvarchar(max)` `SqlServer:Identity` are not for mysql.
