### ISSUE TITLE
.selectpicker() is not a function.

### ISSUE THREAD

**Issue by eng-mohammed-emam** [emonney/QuickApp#42]
1. I downloaded the template from GitHub.
2. Build it after runing npm install.
3. Run it and login successfully.
4. When click on "Preferences", I found the attached error.

".selectpicker() is not a function.".

Any suggestions?

![Uploading select_ a_picker_is_not_a_function.png…]()

**Comment by emonney** [comment]
Please specify the browser and the version of the repository used.

**Comment by eng-mohammed-emam** [comment]
I updated nodejs and typescript and found the problem solved.
