### ISSUE TITLE
QuickApp Template can update but not refresh data on UI.

### ISSUE THREAD

**Issue by Thanatphong** [emonney/QuickApp#49]
Dear Sir,

I used QuickApp - ASP.NET Core/AngularX Project Template on VS 2017. When I updated Job Title on User Profile setting menu, the updated data can save successfully but not show the updated value onscfreen. It's still show the old value before updated.

Can you help please.

thank you.

**Comment by Thanatphong** [comment]
I'm just solve the problem but not sure is it the right way?

I comment below line of code in function "private saveSuccessHelper(user?: User)"

**if (this.isEditingSelf) {
            this.alertService.showMessage("Success", "Changes to your User Profile was saved successfully", MessageSeverity.success);
            //this.refreshLoggedInUser();
        }**

**Comment by emonney** [comment]
What browser and version of QuickApp are you using?
Can you send me a simple project where I can reproduce this?

**Comment by emonney** [comment]
Please reopen if this is still an issue
