### ISSUE TITLE
Add Angular-CLI support

### ISSUE THREAD

**Issue by fmorriso** [emonney/QuickApp#5]
Please consider adding Angular-CLI support for creating the initial Angular 4.x code and for building. 

It might actually simplify things.

**Comment by emonney** [comment]
Great. Angular-cli is definitely in the pipeline. Feel free to send some pull requests on this.

**Comment by fmorriso** [comment]
I would like the best of both worlds: angular-cli for building via ng build plus the server-side power that is part of the template you provide.  

That way, I could ng generate new things that would automatically be picked up by the overall build process (assuming one of the build events is ng build).   There would theoretically be no need for ng serve under the circumstances I envision.
