### ISSUE TITLE
webpack ./node_modules/@angular/core/esm5/core.js

### ISSUE THREAD

**Issue by IngoManthey** [emonney/QuickApp#50]
Hi Dear,
I upgraded the project to version 5.0.1 with npm-upgrade. Because I want to use Angular/Material.
if I call webpack --config webpack.config.vendor.js I get follow warning:
WARNING in ./node_modules/@angular/core/esm5/core.js
    6438:15-36 Critical dependency: the request of a dependency is an expression
     @ ./node_modules/@angular/core/esm5/core.js
     @ dll vendor

Here https://github.com/asadsahi/AspNetCoreSpa/issues/96 I read that is a problem with the  webpack.config.js. 

what can I do.
Thanks for your help.
Regards Ingo

**Comment by IngoManthey** [comment]
I resolve the problem.

**Comment by jcheenatcode** [comment]
@IngoManthey How did you resolve this issue? Was having the same issue.

Thanks

**Comment by IngoManthey** [comment]
@jcheenatcode 
add to webpack.config.vendor.js
new webpack.ContextReplacementPlugin(/\@angular(\\|\/)core(\\|\/)esm5/, path.join(__dirname, './client')),

**Comment by renmengting** [comment]
@IngoManthey 
is this right?
`new webpack.ContextReplacementPlugin(/\@angular(\\|\/)core(\\|\/)esm5/, path.join(__dirname, './ClientApp')),`

**Comment by IngoManthey** [comment]
@renmengting yes I wrote it .
add in plugins:
