### ISSUE TITLE
npm install failed with errors

### ISSUE THREAD

**Issue by jaegerbo** [emonney/QuickApp#51]
Hi,
I use Visual Studio 2017 Version 15.4.4 under Windows 7. Node Veriosn 8.9.1.

I start a new project with this template, but get errors like

`Can't resolve '@angular/common' in .....`

I try 'dotnet restore', and it works.
I try 'npm install' and it brings the following errors:

`error path D:\Projekte\Angular04\Angular04\Angular04\node_modules\hawk\package.json.3634235696
error code EPERM
error errno -4048
error syscall rename
error Error: EPERM: operation not permitted, rename 'D:\Projekte\Angular04\Angular04\Angular04\node_modules\hawk\package.json.3634235696' -> 'D:\Projekte\Angular04\Angular04\Angular04\node_modules\hawk\package.json'
error  { Error: EPERM: operation not permitted, rename 'D:\Projekte\Angular04\Angular04\Angular04\node_modules\hawk\package.json.3634235696' -> 'D:\Projekte\Angular04\Angular04\Angular04\node_modules\hawk\package.json'
error   cause:
error    { Error: EPERM: operation not permitted, rename 'D:\Projekte\Angular04\Angular04\Angular04\node_modules\hawk\package.json.3634235696' -> 'D:\Projekte\Angular04\Angular04\Angular04\node_modules\hawk\package.json'
error      errno: -4048,
error      code: 'EPERM',
error      syscall: 'rename',
error      path: 'D:\\Projekte\\Angular04\\Angular04\\Angular04\\node_modules\\hawk\\package.json.3634235696',
error      dest: 'D:\\Projekte\\Angular04\\Angular04\\Angular04\\node_modules\\hawk\\package.json' },
error   stack: 'Error: EPERM: operation not permitted, rename \'D:\\Projekte\\Angular04\\Angular04\\Angular04\\node_modules\\hawk\\package.json.3634235696\' -> \'D:\\Projekte\\Angular04\\Angular04\\Angular04\\node_modules\\hawk\\package.json\'',
error   errno: -4048,
error   code: 'EPERM',
error   syscall: 'rename',
error   path: 'D:\\Projekte\\Angular04\\Angular04\\Angular04\\node_modules\\hawk\\package.json.3634235696',
error   dest: 'D:\\Projekte\\Angular04\\Angular04\\Angular04\\node_modules\\hawk\\package.json',
error   parent: 'quickapp' }`

Can anybody help me?

**Comment by Maranux** [comment]
Hi Jaegerbo,

Looks to me like you have a permission issue with NPM... Have you tried running npm as root / admin? 

It might also make sense to delete the node_modules folder and restart the npm install instead of worrying about the permissions.

**Comment by emonney** [comment]
Your issue doesn't seem to be related to the template.
Check you have enough permission to make writes/edits to the root folder you're installing your node modules into.
Also like Maranux said, you can delete the node_modules folder, restart your pc and try again.

Closing this ticket, feel free to reopen if issue persists.
