### ISSUE TITLE
it seems the project requires node.js to compile

### ISSUE THREAD

**Issue by kolkonos** [emonney/QuickApp#56]
when building the solution i get this error.
"Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE."

Is this a requirement?  Will it need to be installed on the production server as well?

**Comment by tflanitzer** [comment]
Yes, Node.js is required in the development environment, as it is typically for modern web applications. The typescript transpiler, webpack and various little tools and helpers for testing, minification, live reload are all based on Node.js.

It is not needed in production, however.

**Comment by emonney** [comment]
This is a fundamental requirement for angular projects.
This link might help you to get started: https://angular.io/guide/quickstart
