### ISSUE TITLE
Issues with Login

### ISSUE THREAD

**Issue by ComputingMastery** [emonney/QuickApp#57]
Please update your Migrations for the newer version of OpenIdDict which has made changes to the schema.  This fixes most of the issues folks seem to be having.

**Comment by mudasir** [comment]
do you have a solution, how to fix it ?

**Comment by ComputingMastery** [comment]
Yes...

Make sure you have SQL Loaded locally and both the regular appsettings.json
is pointing to your instance of SQL for both it and the Development setting
hidden underneath.

once you get all the packages down and the app will run, but not login...
gets server errors...

go to the NuGet Package Management Console and type

add-migration "Update for new OpenIdDict"

then

update-database

once those process successfully, the application should run and be able to
login with the credentials provided on the project site with a simple F5

**Comment by emonney** [comment]
Updates to the latest OpenIdDict changes the schema of the database. Apply a new migration to reflect these changes to the database and login will work.
This has been done in the latest commit (Angular5 update) https://github.com/emonney/QuickApp/commit/dd21fda24a1e787c6f9d3a9acf112085a950e63a
