### ISSUE TITLE
Got JS error on Safari Browser !

### ISSUE THREAD

**Issue by AbhiThakare** [emonney/QuickApp#59]
Hi

@emonney  - Thanks for all your efforts, it's awesome project to start with 

I got a JS error on safari, due to which loading page stuck not able to proceed to login page 

I am using safari browser (V:5.1.7 (7534.57.2)), this is reproduced only on safari, on rest of the browser working correct, URL - http://quickapp.ebenmonney.com/ 

Can you please help me here, 

Regards,
Abhi

![image](https://user-images.githubusercontent.com/10028004/33720305-7277bdc4-db5b-11e7-8c05-a3a86974f097.png)

**Comment by emonney** [comment]
This is an issue with one of the polyfills angular uses for animations: web-animations.
There's an open issue here: https://github.com/web-animations/web-animations-js/issues/80
Track the solution from there.

Try going to angular's home page (or other angular sites with animations): e.g. https://angular.io on safari on Windows. Same issue.

**Comment by emonney** [comment]
According to the angular team Safari on Windows is not supported at the moment. Browser version is too old.
See https://angular.io/guide/browser-support for supported browsers
