### ISSUE TITLE
Installation Notes: MSBuild required

### ISSUE THREAD

**Issue by saad749** [emonney/QuickApp#6]
I did not had MS Build installed on my system and was getting different errors, even If I followed the Installation Notes.

Installing  Build Tools for Visual Studio 2017 from https://www.visualstudio.com/downloads/ and checking the Web Development workload fixes the issue.

**Comment by emonney** [comment]
What tools, ide, editors were you using? And on what OS?

PS: Consider submitting a pull request to update the docs to reflect your scenario.

**Comment by saad749** [comment]
I am using VS2017 Community edition on Windows 10.

**Comment by emonney** [comment]
I think your case is a peculiar case. My expectation is Build tools + Roslyn compiler + etc is installed with VS2017 Community edition. At least if you installed the ASP.Net component.
Perhaps your installation was corrupted in some way?
