### ISSUE TITLE
Endpoint-factory-service getRefreshLoginEndpoint

### ISSUE THREAD

**Issue by IngoManthey** [emonney/QuickApp#60]
Once this method is called, it can not be used again because the local storage of the refresh token is saved as undefined.

**Comment by emonney** [comment]
Please provide the steps to reproduce this

**Comment by IngoManthey** [comment]
The problem is that when the program requests a refresh token it gets a new token but no refresh token. The old one will be overwritten as undefined. But I have read in OpenIddict that in version 2.0.0-rc2 the refresh token is transmitted again.

**Comment by IngoManthey** [comment]
Hi,
the problem is resolve by OpenIddict" Version="2.0.0-rc1-0669

**Comment by emonney** [comment]
Yes. This was a behavior change in the OpenIddict library.

**Comment by emonney** [comment]
Fixed in https://github.com/emonney/QuickApp/commit/98f44df7f61d9b5a70a8b90085b9135616773def
