### ISSUE TITLE
How do I create a new simple client object?

### ISSUE THREAD

**Issue by punkouter** [emonney/QuickApp#62]
I create a new simple Survey object which will have a collection of Surveys. I figured out how to set up the server side but the client side is difficult for me. If the Product example the .ts is blank and just refers to the todo controls. 

All I want to do is have a simple list. 

Right now I just call HttpClient directly but I would like to do it the proper way. I am guessing I should use some service. Help  ?

**Comment by emonney** [comment]
Only defects/issues/enhancements are allowed here at this time.
See https://angular.io/tutorial if you need help understanding the angular framework
