### ISSUE TITLE
node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js

### ISSUE THREAD

**Issue by hillgach** [emonney/QuickApp#63]
I'm trying to compile the solution. After compiling I get the following Error:
"Fehler	MSB3073	Der Befehl "node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js" wurde mit dem Code 1 beendet.	CMIB_Services_Platform	C:\Users\X7843\Desktop\CMIB_Services_Platform\CMIB_Services_Platform\CMIB_Services_Platform\CMIB_Services_Platform.csproj	53"
Messages by trying to execute "npm install":
![image](https://user-images.githubusercontent.com/31888753/33911491-d2790db4-df92-11e7-8504-4303911761a9.png)

**Comment by emonney** [comment]
1. Update your node and npm packages from here: https://nodejs.org
2. Delete your node_modules folder and shutdown visual studio
3. Open command prompt and run the following commands from the location of your project
i. npm cache clean
ii. npm install


For support issues please use https://stackoverflow.com. You can then send me a link to the so question.
GitHub issues is reserved for bugs and feature requests.
