### ISSUE TITLE
QuickApp is my First session of learning about Angular! Need help! 

### ISSUE THREAD

**Issue by CS-beglnner** [emonney/QuickApp#67]
Hi,
I'm just start learning Core 2.0 and Angular! I want start researching on Your amazing template for myself!
I read some tutorial about Angular But I can't understanding your Software Architecture. If is possible please tell me "How I can add a new component (e.x Signup or ContactUs Forms) at your template? 
Your answer can be helpful for other starters like me!

Thanks!
Best Regards

**Comment by nvoskuilen** [comment]
My advice is to just start playing around (trail 'n error) with this amazing template. It is quite advanced and really well coded.

**Comment by CS-beglnner** [comment]
@nvoskuilen I'm really student, I like .Net and MS Tech but I don't know where I can start learning. I'm working for a little company at UI department so I know HTML and a bit JS, for now I want learn .Net for myself on my free times. 
At this Template I can't find any Angular Forms sample (Two-Way). I want start my learning at Front-end and bilateral interaction with the user .

**Comment by emonney** [comment]
https://angular.io/tutorial for now. I'll start a series of article early next year to throw more lights on this.
Subscribe to my twitter/youtube to be notified.
