### ISSUE TITLE
Error when deploy to Azure, needs Angular 5 +

### ISSUE THREAD

**Issue by QadMohKuwait** [emonney/QuickApp#71]
Can not deploy the app to Azure, error with Angular version, requesting Angular5+

**Comment by emonney** [comment]
This is a support question. Please post in this forum for the needed assistance. http://www.ebenmonney.com/forum/?view=forum&id=14

We're moving all help & support queries to the [support forum](http://www.ebenmonney.com/forum/?view=forum&id=14). Github issues will only be used for bug reports & tracking
