### ISSUE TITLE
Ticket Authorization Timeout

### ISSUE THREAD

**Issue by mattstobber** [emonney/QuickApp#73]
Sorry for such a simple question, but where do I tweak how long the user cookie lasts? It seems to only last for 30 minutes, and then I start getting 401 unauthorized errors. Thank you.

**Comment by emonney** [comment]
This is a support question. Please post in this forum for the needed assistance. http://www.ebenmonney.com/forum/?view=forum&id=14

We're moving all help & support queries to the [support forum](http://www.ebenmonney.com/forum/?view=forum&id=14). Github issues will only be used for bug reports & tracking
