### ISSUE TITLE
Error in front end app.

### ISSUE THREAD

**Issue by TonyJen** [emonney/QuickApp#77]
Hi, I'm getting an error on the front end portion of the app.

compiler.js:485 Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:485)
    at compiler.js:15206
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15189)
    at JitCompiler._loadModules (compiler.js:34226)
    at JitCompiler._compileModuleAndComponents (compiler.js:34187)
    at JitCompiler.compileModuleAsync (compiler.js:34081)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:230)
    at PlatformRef.bootstrapModule (core.js:5573)
    at Object.<anonymous> (boot.browser.ts:34)

Not sure what the problem is. This is a new installation and new seed so should work out of the box.

**Comment by emonney** [comment]
I checked and couldn't reproduce this on my system.
Please share more information about your envioronment.

OS Version
Node Version
NPM version
Your package.config file since this is a new information (Necessary to determine the client library versions you're using)

Also you can try the following to reset your project packages.
* Delete the node_modules and the dist folder under wwwroot.
* After that run npm install again to redownload all your client packages
* Try running the solution again


Try [QuickApp PRO](http://quickapp-pro.ebenmonney.com/) (Angular CLI, Angular Material, IdentityServer4, etc)

**Comment by TonyJen** [comment]
Hi, when I was using Angular 4.x the application worked fine.  It started when I upgrade to angular 5

My OS is windows 10.
node version:  9.4
Npm version : 5.6

Note I was able to delete the node_modules directory but now when I run npm install I get this error:

22905 verbose Windows_NT 10.0.16299
22906 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
22907 verbose node v9.4.0
22908 verbose npm  v5.6.0
22909 error path D:\Projects\QuickApp\src\QuickApp\node_modules\electron-releases\package.json.3956419734
22910 error code EPERM
22911 error errno -4048
22912 error syscall rename
22913 error Error: EPERM: operation not permitted, rename 'D:\Projects\QuickApp\src\QuickApp\node_modules\electron-releases\package.json.3956419734' -> 'D:\Projects\QuickApp\src\QuickApp\node_modules\electron-releases\package.json'
22913 error  { Error: EPERM: operation not permitted, rename 'D:\Projects\QuickApp\src\QuickApp\node_modules\electron-releases\package.json.3956419734' -> 'D:\Projects\QuickApp\src\QuickApp\node_modules\electron-releases\package.json'
22913 error   cause:
22913 error    { Error: EPERM: operation not permitted, rename 'D:\Projects\QuickApp\src\QuickApp\node_modules\electron-releases\package.json.3956419734' -> 'D:\Projects\QuickApp\src\QuickApp\node_modules\electron-releases\package.json'
22913 error      errno: -4048,
22913 error      code: 'EPERM',
22913 error      syscall: 'rename',
22913 error      path: 'D:\\Projects\\QuickApp\\src\\QuickApp\\node_modules\\electron-releases\\package.json.3956419734',
22913 error      dest: 'D:\\Projects\\QuickApp\\src\\QuickApp\\node_modules\\electron-releases\\package.json' },
22913 error   stack: 'Error: EPERM: operation not permitted, rename \'D:\\Projects\\QuickApp\\src\\QuickApp\\node_modules\\electron-releases\\package.json.3956419734\' -> \'D:\\Projects\\QuickApp\\src\\QuickApp\\node_modules\\electron-releases\\package.json\'',
22913 error   errno: -4048,
22913 error   code: 'EPERM',
22913 error   syscall: 'rename',
22913 error   path: 'D:\\Projects\\QuickApp\\src\\QuickApp\\node_modules\\electron-releases\\package.json.3956419734',
22913 error   dest: 'D:\\Projects\\QuickApp\\src\\QuickApp\\node_modules\\electron-releases\\package.json',
22913 error   parent: 'quickapp' }
22914 error Please try running this command again as root/Administrator.
22915 verbose exit [ -4048, true ]

**Comment by TonyJen** [comment]
I think the problem is related to my user account. Thanks for the help.
