### ISSUE TITLE
[Angular Project in Angular CLI]

### ISSUE THREAD

**Issue by kennyboda** [emonney/QuickApp#78]
Hi,

Is there any way to compile the Angular 5 project part in the cmd line using the Angular CLI (ng commands)?

Because I think it is simpler to work in Visual Studio Code to create the angular part and to compile it.

Best regards.

**Comment by emonney** [comment]
Angular CLI is not integrated in this version. For a version with Angular CLI you can try [QuickApp PRO](http://ebenmonney.com/product/quickapp-pro/)

The alternative is to use standard node commands to build the project.
* Build Client packages: node node_modules/webpack/bin/webpack.js --env.prod
* Build Vendor packages: node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod

These are not friendly commands to memorize. So I suggest adding it to the script segment in package.json for easier access
