### ISSUE TITLE
Unable to login - The specified 'Content-Type' header is not valid.

### ISSUE THREAD

**Issue by Sami-L** [emonney/QuickApp#80]
Unexpectedly and without any code change, the template stopped working. I enter the right user name and password but fail to login receiving the following error message: 

Unable to login 
The specified 'Content-Type' header is not valid.

any idea ?

**Comment by emonney** [comment]
In order to login to the token endpoint you need the 'Content-Type': 'application/x-www-form-urlencoded'.
Look in the file "endpoint-factory.service.ts" from the `getLoginEndpoint` method. What do you have there?

**Comment by Sami-L** [comment]
here is the code snippet:

`    getLoginEndpoint<T>(userName: string, password: string): Observable<T> {

        let header = new HttpHeaders({ 'Content-Type': 'application/x-www-form-urlencoded' });

        let params = new HttpParams()
            .append('username', userName)
            .append('password', password)
            .append('grant_type', 'password')
            .append('scope', 'openid email phone profile offline_access roles')
            .append('resource', window.location.origin);

        let requestBody = params.toString();

        return this.http.post<T>(this.loginUrl, requestBody, { headers: header });
    }`

Compared to the original, it's identical.

**Comment by prvit** [comment]
I faced the same issue. Before, it was working even sendint application/json Content-Type. Now, even sending application/x-www-form-urlencoded is not working.

![image](https://user-images.githubusercontent.com/2816799/35278924-28dde9e0-0054-11e8-92aa-6c0a76feec3e.png)

The worst thing is I can't debug it, break point on the the first line of method Exchange is never hit. 
Response:
{"error":"invalid_request","error_description":"The specified 'Content-Type' header is not valid."}

**Comment by emonney** [comment]
I believe you updated openiddict nuget package to a version with a breaking change.
This library was in beta and had breaking changes with each update.
Its currently in rc-final and fairly stable.
Update your project to the latest version of openiddict (or to the one in this repository) and also update your project to match these two files [AuthorizationController.cs](https://github.com/emonney/QuickApp/blob/master/src/QuickApp/Controllers/AuthorizationController.cs) and [endpoint-factory.service.ts](https://github.com/emonney/QuickApp/blob/master/src/QuickApp/ClientApp/app/services/endpoint-factory.service.ts)
