### ISSUE TITLE
Login credentials not accepted on demo site

### ISSUE THREAD

**Issue by beefydog** [emonney/QuickApp#81]
Just to let whoever is in charge of the demo site that both login credentials fail to work.
user/TempP@ss123
and 
admin/TempP@ss123
neither of which work.  Would love to see this demo work!

**Comment by emonney** [comment]
This was probably due to a temporal account lockout due to incorrect multiple password attempts.
I checked and its working now.
I'll disable password lockout on my next publish to the demo site.
Thanks for pointing this out
