### ISSUE TITLE
Issue in Quick App Pro. Cancel Button in User Profile 

### ISSUE THREAD

**Issue by codestellar** [emonney/QuickApp#82]
Cancel button is not working in Edit User Profile

**Comment by emonney** [comment]
I checked from the demo page and its working. How do you reproduce it?

**Comment by codestellar** [comment]
Sorry for late reply!
I checked in the demo page and it is not working. Go to Settings > Edit Profile > Cliick on Cancel and it does not work.
![image](https://user-images.githubusercontent.com/17561784/35846581-41b8c086-0b3d-11e8-8801-8ce0de435204.png)

**Comment by codestellar** [comment]
@emonney can you please re-open this issue

**Comment by emonney** [comment]
@codestellar Sorry I assumed this was the Open Source version. Yes I was able to reproduce this.
The fix is to add the line `this.isEditMode = false` to the `cancel()` function in "_user-editor.component.ts_".
Also change its access modifier from private to public.
So it becomes:

```
    public cancel() {
        this.resetForm();
        this.isEditMode = false;

        this.alertService.resetStickyMessage();
    }
```

**Comment by emonney** [comment]
This was fixed in the recent update. Please redownload the sourcecode to get the fix.
