### ISSUE TITLE
Seperate repo for ClientApp?

### ISSUE THREAD

**Issue by nvoskuilen** [emonney/QuickApp#85]
So one could use angular-cli with Visual Studio Code to develop the front end.

Contributors with Angular only skills could join more easily, and likewise ASP skilled folks could contribute the backing.

**Comment by emonney** [comment]
I'm working on a bootstrap4 version with angular CLI and IdentityServer 4. It'll be available soon.

**Comment by emonney** [comment]
Starting with commit 21880e982f9d3666f3d7b3702a1a91f54a580cdd the client part uses Angular CLI.
To separate the 2 projects simply copy out the "ClientApp" folder and work on it as you would any angular CLI project.
