### ISSUE TITLE
Register Form

### ISSUE THREAD

**Issue by xjose97x** [emonney/QuickApp#86]
I was wondering how would be the best way to create a register route with this project.

I plan to add a form in angular for new users to register.

**Comment by codestellar** [comment]
@xjose97x you should ask this question in forum:
https://www.ebenmonney.com/forum/?view=forum&id=14

**Comment by emonney** [comment]
Please see this forum topic for a similar discussion: https://www.ebenmonney.com/forum/?view=thread&id=9&part=1#postid-31
