### ISSUE TITLE
Can't get userID when logged in on an anonymous page

### ISSUE THREAD

**Issue by thewebchameleon** [emonney/QuickApp#91]
I am trying to implement a shopping cart and I can't access the User ID from the HttpUnitOfWork class when I am on an anonymous page. 

The method in question is
HttpContext?.User.FindFirst(ClaimConstants.Subject)
or HttpContext?.User.FindFirst(OpenIdConnectConstants.Claims.Subject)

The bearer token is being passed through on the request and when I hit a page with an Authorize attribute then I have full access to the claims.

Is this expected behaviour? Is there a way to manually get the user from the bearer token in the request header?

**Comment by Owned333** [comment]
@thewebchameleon  how did you solve this problem? I also try to get the current user in my controller, but I did not get it. Can you help me?

**Comment by pomeara** [comment]
Ensure you have access to the user manager (just inject it into the constructor) and then return you should be able to use it to retrieve the user from the HttpContext user i.e. 

_userManager.GetUserId(HttpContext.User);

**Comment by Owned333** [comment]
I Tried this, It's seems like User in HttpContext is always null, but the
user is logged in. I can not understand what the problem is, help :)

2018-07-06 2:04 GMT+03:00 pomeara <notifications@github.com>:
