### ISSUE TITLE
HTTPErrorResponse Creating User

### ISSUE THREAD

**Issue by joeg10** [emonney/QuickApp#93]
I'm receiving the errors below when calling AccountController.Register.  When stepping through the code is see that the method hits the correct return and userVM is correct.  I'm  using your Pro template, can you help me out please?  Thanks

**This is being hit** - CreatedAtAction(GetUserByIdActionName, new { id = userVM.Id }, userVM);

**These are the errors:**

Failed to load resource: net::ERR_CONNECTION_RESET
alert.service.ts:176 Severity: "error", Summary: "Save Error", Detail: "One or more errors occured whilst saving your changes:", Error: "{"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":null,"ok":false,"name":"HttpErrorResponse","message":"Http failure response for (unknown url): 0 Unknown Error","error":{"isTrusted":true}}"

**Comment by Sami-L** [comment]
I have got this error after I changed the environment.ts url address from **null** to the address of my backend API '**http://localhost:5000**'

**Comment by joeg10** [comment]
This turned out to be a json serialization issue for me.  Simplifying the returned fixed the issue.
