### ISSUE TITLE
HTTPErrorResponse Loging in. Trying backend and frontend from separate projects.

### ISSUE THREAD

**Issue by AnassL** [emonney/QuickApp#94]
@emonney, I want to buy your pro version of this template, but first I need to ensure it can work in a separate frontend/backend manner. I need to have them in totally autonomous projects.

To host backend on a different url, I changed the url address in the environment.ts file from **null** to  '**http://localhost:5000**'

When I try to log in, the app shows the modal message: "Dear Developer! It appears your backend Web API service is not running... 
After deactivated it from login.component.ts, I get now the error message "No Network" and "The server cannot be reached"

so, what if one would like to use localhost for the backend to test developing some APIs stuff before pushing them to the production server ?

Also what if one would like to use localhost on the production server to host the backend, and use a domain name for hosting the frontend on the same production server ?

**Is there a special reason for which you banned the localhost usage ?**

Then I wanted to try not to use localhost for the moment, I hosted the app backend using a domain name, let's say "domain.com". In the frontend I configured environment.ts as next:

```
export const environment = {
    production: false,
    baseUrl: 'http://domain.com', 
    loginUrl: '/Login'
};
```

But I get the following error:

> No '**Access-Control-Allow-Origin**' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 500.

CORS is at its original state in startup.cs, what am I missing ?

**Comment by rb4bhushan** [comment]
I am also trying to separate front-end and back-end so that I can run both separately. My priority is to run front-end without running back-end services using some type of mock data. Can you guys help me with that.

**Comment by emonney** [comment]
There's no restriction to the type of backend address you can use. localhost is NOT banned.
From [this commit](https://github.com/emonney/QuickApp/commit/21880e982f9d3666f3d7b3702a1a91f54a580cdd) onwards the project uses a standalone angular Cli project that can work independently from the asp.net core backend. You treat it as you would any other standard angular cli project.
Try connecting your backend to a tool like postman and make sure its responsive and returning the expected results. Also if you're using any version prior to the commit stated above try updating to a newer version.
Since this is an old post I'll go ahead and close it. Feel free to reopen it if this is still an issue.

**Comment by sramkumarmca** [comment]
still getting same error ... i splitted the project into microservice... if i access my own  API from angular project, i am getting  error 'No 'Access-Control-Allow-Origin' header is present on the requested resource. 

service is working in postman.

**Comment by Mynken** [comment]
> still getting same error ... i splitted the project into microservice... if i access my own API from angular project, i am getting error 'No 'Access-Control-Allow-Origin' header is present on the requested resource.
> now i have 3 project
> 
> 1. auth server
> 2. angular
>    3.web api
>    issue: angular project cannot access form web api , but can access from auth server
> 
> service is working in postman.

Please post your request from angular.

**Comment by AnassL** [comment]
Using separate auth server is a great practice, but you'll need now to reference in  angular two endpoints ports, one for the auth server as log in url and the other for the resource server apis.

Has anyone tried to configure auth server to use EntityFramework (EF) as the storage mechanism for configuration data, rather than using the in-memory implementations ?
