### ISSUE TITLE
database for this app

### ISSUE THREAD

**Issue by dineshthigale** [emonney/QuickApp#96]
how create the database for this quick app?

**Comment by liphis** [comment]
If you have LocalDB installed (with Visual Studio), a LocalDB database will be created by applying the migration on Run. See Program.cs -> databaseInitializer.SeedAsync().Wait();
Initial migration is provided in the sources. If you want to use another type db, you'll have to regenerate the migrations file after you change the DefaultConnection string in appsettings.json

**Comment by idontbyte** [comment]
Here are the steps I took to use full SQL Server database:

1. Create new blank database in SQL Express or SQL Server.
2. Change connection string in appsettings.json / appsettings.Development.json
3. Add a migration in package manager console by using the command:
add-migration "migration name"
4. Apply tables to database in package manager console  by using the command:
update-database

**Comment by pomeara** [comment]
I would like to know how to remove the .NET Standard DAL and make it a .NET Core app as the back end is a single DLL that's not well seperated
On 20 Jun. 2018, at 11:54 pm, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:

Here are the steps I took to use full SQL Server database:

  1.  Create new blank database in SQL Express or SQL Server.
  2.  Change connection string in appsettings.json / appsettings.Development.json
  3.  Add a migration in package manager console by using the command:
add-migration "migration name"
  4.  Apply tables to database in package manager console by using the command:
update-database

**Comment by emonney** [comment]
For Ms SQL type databases (SQL Express, SQL Server, LocalDB, ...) what you have to do is make sure the connection string points to the database of your choice and the credentials used has the rights to create databases and tables on the target server. You then run your application and everything will be created for you **automatically** using migrations.
